package br.com.lpr.core.util;

import br.com.lpr.core.model.dto.PublicacaoElasticDTO;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class PublicacaoBuilderTemporaryUtil {

    public static List<PublicacaoElasticDTO> build(){
        List<PublicacaoElasticDTO> list = new ArrayList();
        list.add(PublicacaoElasticDTO.builder()
                .id(1L)
                .titulo("GenGame: Associação do Uso de Fábrica de Aplicativos com Geradores de Código para Games em Dispositivos Móveis")
                .palavrasChave(Arrays.asList("Jogos", "Fábrica de Aplicativos", "Android", "Gerador de Código"))
                .autor("Arthur Santos de Araújo").lattes("NSA").orientador("Eduardo Manoel de Freitas Jorge")
                .dataDeposito("2016-05-16").dataDefesa("2016-05-16")
                .resumo("A área dos dispositivos móveis tem crescido exponencialmente nos últimos anos e um seguimento neste contexto que vem se destacando é o de jogos. No entanto, o desenvolvimento de um jogo mobile é algo complexo e muitas vezes custoso. O mercado possui uma alta demanda imediatista destes, fazendo com que cada vez mais seja necessário otimizar os métodos de desenvolvimento, resultando normalmente na redução do ciclo de criação e no custo do projeto. O presente trabalho propõe a especificação e construção de um gerador de código para jogos em dispositivos móveis que segue a linha de uma fábrica de aplicativos, chamado de GenGame. Solução esta que permite a personalização inicial por parte do usuário e gera o código do projeto já customizado na plataforma Android. Para validação e verificação da solução proposta foram construídos dois jogos denominados Terra do Gelo - Tiro e Terra do Gelo - Locomover")
                .conteudoArquivo("A área dos dispositivos móveis tem crescido exponencialmente nos últimos anos e um seguimento neste contexto que vem se destacando é o de jogos. No entanto, o desenvolvimento de um jogo mobile é algo complexo e muitas vezes custoso. O mercado possui uma alta demanda imediatista destes, fazendo com que cada vez mais seja necessário otimizar os métodos de desenvolvimento, resultando normalmente na redução do ciclo de criação e no custo do projeto. O presente trabalho propõe a especificação e construção de um gerador de código para jogos em dispositivos móveis que segue a linha de uma fábrica de aplicativos, chamado de GenGame. Solução esta que permite a personalização inicial por parte do usuário e gera o código do projeto já customizado na plataforma Android. Para validação e verificação da solução proposta foram construídos dois jogos denominados Terra do Gelo - Tiro e Terra do Gelo - Locomover...")
                .build());

        list.add(PublicacaoElasticDTO.builder()
                .id(2L)
                .titulo("Arquitetura de Referência para Softwares de Indexação e Recuperação de Documentos nas Universidades Aplicando Técnicas de SEO")
                .palavrasChave(Arrays.asList("SEO", "Repositório Institucional", "Arquitetura de referência"))
                .autor("Gustavo Santana Araújo").lattes("http://lattes.cnpq.br/4399335280530428").orientador("Eduardo Manoel de Freitas Jorge")
                .dataDeposito("2016-05-25").dataDefesa("2016-05-25")
                .resumo("A divulgação da produção científica das Universidades é de suma importância atualmente, e se destacar no meio de tanta informação é um desafio constante. Por isso surge a pergunta: como ampliar a visibilidade dos trabalhos científicos elaborados na UNEB utilizando técnicas de SEO - que pode ser definido como técnicas para otimização de sites para mecanismos de busca na web. Essa pesquisa propõe uma arquitetura de referência cujo requisito principal é melhor ranquear os trabalhos científicos, produzidos na instituição, nas principais ferramentas de busca conhecidas. Os Repositórios Institucionais apresentam uma opção para esse projeto já que implementam a parte da gestão dos documentos produzidos. Para medir o sucesso da instância da arquitetura, é preciso que a solução seja indexada pelos buscadores para que as técnicas de SEO ajam e melhorem o ranqueamento dos itens presentes na arquitetura de referência. Os resultados da aplicação dessas técnicas podemser percebidos quando o retorno possui um ranqueamento vantajoso em relação a quantidade de resultados")
                .conteudoArquivo("A divulgação da produção científica das Universidades é de suma importância atualmente, e se destacar no meio de tanta informação é um desafio constante. Por isso surge a pergunta: como ampliar a visibilidade dos trabalhos científicos elaborados na UNEB utilizando técnicas de SEO - que pode ser definido como técnicas para otimização de sites para mecanismos de busca na web. Essa pesquisa propõe uma arquitetura de referência cujo requisito principal é melhor ranquear os trabalhos científicos, produzidos na instituição, nas principais ferramentas de busca conhecidas. Os Repositórios Institucionais apresentam uma opção para esse projeto já que implementam a parte da gestão dos documentos produzidos. Para medir o sucesso da instância da arquitetura, é preciso que a solução seja indexada pelos buscadores para que as técnicas de SEO ajam e melhorem o ranqueamento dos itens presentes na arquitetura de referência. Os resultados da aplicação dessas técnicas podemser percebidos quando o retorno possui um ranqueamento vantajoso em relação a quantidade de resultados...")
                .build());

        list.add(PublicacaoElasticDTO.builder()
                .id(3L)
                .titulo("ANÁLISE COMPARATIVA DE SOLUÇÕES EM SOFTWARE DA GERÊNCIA DE PROJETOS E SUA ADERÊNCIA AO GUIA DO PMI")
                .palavrasChave(Arrays.asList("Tecnologia da Informação", "Gerente de projetos", "Ger"))
                .autor("MARLENA MOTA MARTINS").lattes("NSA").orientador("Ana Patrícia Fontes Magalhães Mascarenhas\n")
                .dataDeposito("2016-05-25").dataDefesa("2016-05-25")
                .resumo("Durante muitos anos o desenvolvimento de produtos e serviços de tecnologia foram realizados de maneira ad-hoc, sem a utilização de técnicas que pudessem nortear esse desenvolvimento. Como consequência, eram gerados softwares que não atendiam às expectativas dos clientes e que ultrapassavam os limites de custo e prazo inicialmente planejados. Para contribuir na melhora desse cenário, a gerência de projetos está inserida buscando equilibrar, planejar, organizar e administrar objetivos específicos com prazo, custo e qualidade determinados, para satisfazer os envolvidos no projeto. Desta forma, aplica instrumentos, capacidades, conhecimentos e técnicas de modo a atender os requisitos do projeto. Particularmente, este trabalho utiliza o PMBOK, um guia de boas práticas proposto pelo PMI, já conhecido e validado, que visa normalizar conhecimentos, técnicas e termos amplamente utilizados na Gerência de Projetos. O PMBOK compreende 47 processos, que se complementam para compor o que chamamos de ciclo do projeto. Em apoio a execução desses processos, ferramentas diversas foram propostas ao longo dos anos. Contudo, escolher a ferramenta mais adequada ao projeto é um processo penoso e conta com muito tempo dedicado ao estudo e aperfeiçoamento no uso da ferramenta, além do risco da ferramenta não corresponder ao que é necessário ao projeto. Esta monografia apresenta uma análise comparativa de soluções em software da área de gerência de projetos e objetiva fundamentar a escolha da ferramenta mais adequada ao tipo de projeto proposto, minimizando os riscos e o impacto causado pelo tempo gasto pelos gerentes na escolha da melhor ferramenta. A análise foi conduzida através de uma avaliação quantitativa com o estudo e uso contínuo de algumas ferramentas, julgadas segundo sua aderência aos processos do guia PMBOK. Para complementar, foi realizada uma análise qualitativa com base em um questionário aplicado à gerentes de projeto experientes, com o objetivo de adicionar uma visão especialista a pesquisa. Os resultados apontaram uma significativa discrepância na quantidade de usuários dos softwares escolhidos. Apontaram também, que há ferramentas mais genéricas que cumprem um número maior de processos e há ferramentas mais específicas que, apesar de cumprirem um número mais limitado de processos o fazem com melhor desempenho. Os resultados deste trabalho foram aplicados ao mundo real, em um aplicativo mobile desenvolvido na plataforma Android chamado Keindike SWGP.")
                .conteudoArquivo("Durante muitos anos o desenvolvimento de produtos e serviços de tecnologia foram realizados de maneira ad-hoc, sem a utilização de técnicas que pudessem nortear esse desenvolvimento. Como consequência, eram gerados softwares que não atendiam às expectativas dos clientes e que ultrapassavam os limites de custo e prazo inicialmente planejados. Para contribuir na melhora desse cenário, a gerência de projetos está inserida buscando equilibrar, planejar, organizar e administrar objetivos específicos com prazo, custo e qualidade determinados, para satisfazer os envolvidos no projeto. Desta forma, aplica instrumentos, capacidades, conhecimentos e técnicas de modo a atender os requisitos do projeto. Particularmente, este trabalho utiliza o PMBOK, um guia de boas práticas proposto pelo PMI, já conhecido e validado, que visa normalizar conhecimentos, técnicas e termos amplamente utilizados na Gerência de Projetos. O PMBOK compreende 47 processos, que se complementam para compor o que chamamos de ciclo do projeto. Em apoio a execução desses processos, ferramentas diversas foram propostas ao longo dos anos. Contudo, escolher a ferramenta mais adequada ao projeto é um processo penoso e conta com muito tempo dedicado ao estudo e aperfeiçoamento no uso da ferramenta, além do risco da ferramenta não corresponder ao que é necessário ao projeto. Esta monografia apresenta uma análise comparativa de soluções em software da área de gerência de projetos e objetiva fundamentar a escolha da ferramenta mais adequada ao tipo de projeto proposto, minimizando os riscos e o impacto causado pelo tempo gasto pelos gerentes na escolha da melhor ferramenta. A análise foi conduzida através de uma avaliação quantitativa com o estudo e uso contínuo de algumas ferramentas, julgadas segundo sua aderência aos processos do guia PMBOK. Para complementar, foi realizada uma análise qualitativa com base em um questionário aplicado à gerentes de projeto experientes, com o objetivo de adicionar uma visão especialista a pesquisa. Os resultados apontaram uma significativa discrepância na quantidade de usuários dos softwares escolhidos. Apontaram também, que há ferramentas mais genéricas que cumprem um número maior de processos e há ferramentas mais específicas que, apesar de cumprirem um número mais limitado de processos o fazem com melhor desempenho. Os resultados deste trabalho foram aplicados ao mundo real, em um aplicativo mobile desenvolvido na plataforma Android chamado Keindike SWGP....")
                .build());

        list.add(PublicacaoElasticDTO.builder()
                .id(4L)
                .titulo("Uso de Design Thinking na Detecção de Funcionalidades Desejáveis para Ferramentas de Gerenciamento de Arquivos")
                .palavrasChave(Arrays.asList("Design Thinking", "Usabilidade", "Prototipação"))
                .autor("Kelly Bregonci Silva").lattes("NSA").orientador("Eduardo Manoel de Freitas Jorge")
                .dataDeposito("2016-05-30").dataDefesa("2016-05-30")
                .resumo("Em meio a um mundo globalizado, onde com o advento da internet as informações fluem de maneira rápida, as pessoas têm armazenado cada vez mais informações em seus computadores e dispositivos móveis. Diante disso é crescente a necessidade de ferramentas que auxiliem os usuários no processo de recuperar essas informações armazenadas de forma simples e intuitiva. Essa pesquisa tem como objetivo detectar funcionalidades desejáveis para ferramentas de gerenciamento de arquivos tendo como norte a utilização de uma técnica que foca na interação entre usuários e desenvolvedores e usuários e o sistema. Foi utilizado o design thinking (DT) a fim de verificar as necessidades e desejos dos usuários no que tange a utilização de ferramentas de gerenciamento, a partir das informações coletadas foi elaborado um protótipo que foi avaliado tendo conceitos de usabilidade como critérios para a análise. A partir dos resultados obtidos com essa avaliação o protótipo foi refinado e reavaliado. Os resultados obtidos nessa pesquisa apontam para a validade da utilização do design thinking e usabilidade na concepção de sistemas, visto que atinge o objetivo de entender o usuário e disponibilizar o que eles necessitam")
                .conteudoArquivo("Em meio a um mundo globalizado, onde com o advento da internet as informações fluem de maneira rápida, as pessoas têm armazenado cada vez mais informações em seus computadores e dispositivos móveis. Diante disso é crescente a necessidade de ferramentas que auxiliem os usuários no processo de recuperar essas informações armazenadas de forma simples e intuitiva. Essa pesquisa tem como objetivo detectar funcionalidades desejáveis para ferramentas de gerenciamento de arquivos tendo como norte a utilização de uma técnica que foca na interação entre usuários e desenvolvedores e usuários e o sistema. Foi utilizado o design thinking (DT) a fim de verificar as necessidades e desejos dos usuários no que tange a utilização de ferramentas de gerenciamento, a partir das informações coletadas foi elaborado um protótipo que foi avaliado tendo conceitos de usabilidade como critérios para a análise. A partir dos resultados obtidos com essa avaliação o protótipo foi refinado e reavaliado. Os resultados obtidos nessa pesquisa apontam para a validade da utilização do design thinking e usabilidade na concepção de sistemas, visto que atinge o objetivo de entender o usuário e disponibilizar o que eles necessitam...")
                .build());

        list.add(PublicacaoElasticDTO.builder()
                .id(5L)
                .titulo("Um algoritmo de Roteamento para o Boost.Http")
                .palavrasChave(Arrays.asList("CROW", "Boost", "Http", "Roteamento","URL","IO Assíncrono"))
                .autor("Uisleandro Costa dos Santos").lattes("http://lattes.cnpq.br/1559308590958526").orientador("Diego Gervasio Frias Suarez\n")
                .dataDeposito("2016-06-10").dataDefesa("2016-06-10")
                .resumo("A linguagem C++, embora considerada difícil por alguns, por possuir funções de baixo nível, e por possuir problemas de compatibilidade nos diversos sistemas operacionais, vem sofrendo mudanças no sentido de tornar esta linguagem mais constante, com poucas modificações nos diversos sistemas operacionais, sem perder performance. Um dos grupos que tem influenciado bastante o processo de padronização da linguagem é o grupo que criou e mantem o conjunto de bibliotecas Boost. Um dos projetos que estão em discussão no Boost, é o Boost.Http, que dá suporte ao protocolo HTTP, e conta com um modelo de concorrência baseado em IO Assíncrono. O Boost.Http, no entanto, não possui suporte ao Roteamento de URLs, o que implica que o desenvolvedor Boost.Http precisa criar o mapeamento das URLs para as funções correspondentes no código. Este trabalho teve como objetivo principal prover uma camada de Roteamento para o Boost.Http, possibilitando assim que quem optar por usar esta biblioteca, possa se preocupar com outras questões e não com roteamento. Tendo desenvolvido e testado dois algoritmos de roteamento para o Boost.Http, abordou-se como segundo objetivo, a comparação do Boost.Http com outras tecnologias de desenvolvimento web, para obter uma visão geral, no que diz respeito ao desempenho, que poderia fazer com que alguém pudesse decidir usar o Boost.Http para desenvolver aplicações web. Foram desenvolvidas aplicações em CROW, PHP e Boost.Http contendo as mesmas funcionalidades e as mesmas mensagens de retorno para as Rotas que foram pré-definidas durante o processo de testes de cobertura de código. Foram feitos testes de carga usando a mesma ferramenta, nas mesmas condições de configuração de ambiente. A partir dos testes, foi possível observar que o CROW teve um resultado melhor do que o Boost.Http com roteamento. Então optou-se por testar o Boost.Http sem roteamento e observou-se que ainda assim o CROW teve um resultado melhor e que o roteamento.não comprometeu significativamente o desempenho das aplicações desenvolvidas com Boost.Http, no caso de teste considerado. As aplicações em C++, desenvolvidas com CROW e com Boost.Http, tiveram um desempenho melhor do que a aplicação desenvolvida em linguagem PHP. Os resultados sugerem que o CROW permite desenvolver aplicações de melhor performance, no entanto, não possui uma comunidade de usuários tão ampla, nem uma variedade de frameworks e tutoriais, como o PHP, o que deve ser levado em conta na tomada de decisão.\n")
                .conteudoArquivo("A linguagem C++, embora considerada difícil por alguns, por possuir funções de baixo nível, e por possuir problemas de compatibilidade nos diversos sistemas operacionais, vem sofrendo mudanças no sentido de tornar esta linguagem mais constante, com poucas modificações nos diversos sistemas operacionais, sem perder performance. Um dos grupos que tem influenciado bastante o processo de padronização da linguagem é o grupo que criou e mantem o conjunto de bibliotecas Boost. Um dos projetos que estão em discussão no Boost, é o Boost.Http, que dá suporte ao protocolo HTTP, e conta com um modelo de concorrência baseado em IO Assíncrono. O Boost.Http, no entanto, não possui suporte ao Roteamento de URLs, o que implica que o desenvolvedor Boost.Http precisa criar o mapeamento das URLs para as funções correspondentes no código. Este trabalho teve como objetivo principal prover uma camada de Roteamento para o Boost.Http, possibilitando assim que quem optar por usar esta biblioteca, possa se preocupar com outras questões e não com roteamento. Tendo desenvolvido e testado dois algoritmos de roteamento para o Boost.Http, abordou-se como segundo objetivo, a comparação do Boost.Http com outras tecnologias de desenvolvimento web, para obter uma visão geral, no que diz respeito ao desempenho, que poderia fazer com que alguém pudesse decidir usar o Boost.Http para desenvolver aplicações web. Foram desenvolvidas aplicações em CROW, PHP e Boost.Http contendo as mesmas funcionalidades e as mesmas mensagens de retorno para as Rotas que foram pré-definidas durante o processo de testes de cobertura de código. Foram feitos testes de carga usando a mesma ferramenta, nas mesmas condições de configuração de ambiente. A partir dos testes, foi possível observar que o CROW teve um resultado melhor do que o Boost.Http com roteamento. Então optou-se por testar o Boost.Http sem roteamento e observou-se que ainda assim o CROW teve um resultado melhor e que o roteamento.não comprometeu significativamente o desempenho das aplicações desenvolvidas com Boost.Http, no caso de teste considerado. As aplicações em C++, desenvolvidas com CROW e com Boost.Http, tiveram um desempenho melhor do que a aplicação desenvolvida em linguagem PHP. Os resultados sugerem que o CROW permite desenvolver aplicações de melhor performance, no entanto, não possui uma comunidade de usuários tão ampla, nem uma variedade de frameworks e tutoriais, como o PHP, o que deve ser levado em conta na tomada de decisão.\n...")
                .build());
        return list;
    }
}
